sudo: required

language: node_js
node_js:
  - "7"

services:
    - docker

script:
    - ./test-build.sh $NODE_VERSION

env:
    matrix :
        - NODE_VERSION: '6.10'
        - NODE_VERSION: '7.8'
