sudo: required

services:
  - docker
branches:
  only:
    - master

script:
  - docker build -t piezzo/kindlebridge:latest .

after_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push piezzo/kindlebridge:latest
